---@class DBCFTechData
---@field public ID
---@field public NameKey
---@field public Icon
---@field public GID
---@field public RelationID
---@field public NeedTechCenterLev
---@field public MaxLev
---@field public UpgradeTimeMin
---@field public UpgradeTimeMax
---@field public UpgradeTimeCurve
---@field public UpgradeCostGoldMin
---@field public UpgradeCostGoldMax
---@field public UpgradeCostGoldCurve